theme: jekyll-theme-modernist

# A dummy repository or the theme won't build
repository: MichaelCurrin/my-github-projects
author: Michael Currin

render_with_liquid: false

# Using jekyll-theme-architect 0.2.0
# Using minima 2.5.1
# Using jekyll-theme-dinky 0.2.0
# Using jekyll-theme-midnight 0.2.0
# Using jekyll-theme-minimal 0.2.0
# Using jekyll-theme-modernist 0.2.0
# Using jekyll-theme-primer 0.6.0
# Using jekyll-theme-slate 0.2.0
# Using jekyll-theme-time-machine 0.2.0
# Using jekyll-theme-leap-day 0.2.0
# Using jekyll-theme-merlot 0.2.0
# Using jekyll-theme-tactile 0.2.0
# Using jekyll-theme-cayman 0.2.0
# Using jekyll-theme-hacker 0.2.0
